spring:
  application:
    name: FRONT-SERVICE
  profiles:
    active: test

eureka:
  client:
    enabled: true


server:
  port: 8080

oauth:
  payco:
    client_id: 3RDwMkWpqVbBXbEs0f7uAo9
    redirect-uri:

