# 워크플로우에 이름 지정
name: toDevelopMerge

# 현재 워크플로우를 사용한 유저의 이름을 출력
run-name: ${{ github.actor }} is learning GitHub Actions
# 2 워크플로우가 시작됭 조건 지정
on:
  push:
    branches: [master]
  pull_request:
    branches: [master,develop]
    types: [opened, synchronize, reopened]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
