# 워크플로우에 이름 지정
name: toDevelopMerge

# 현재 워크플로우를 사용한 유저의 이름을 출력
run-name: ${{ github.actor }} is learning GitHub Actions
# 2 워크플로우가 시작됭 조건 지정
on:
  push:
    branches: [master]
  pull_request:
    branches: [master,develop]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test tags'
        required: false

#test
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run SonarQube
        run: mvn sonar:sonar -Dsonar.projectKey=github-action -Dsonar.host.url=${{ secrets.SONAR_HOST }} -Dsonar.login=${{ secrets.SONAR_TOKEN_40 }}
      
      - name: upload file
        uses: appleboy/scp-action@develop
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "target/*.jar"
          target: "~/"
          rm: false
      
      - name: execute shell script
        uses: appleboy/ssh-action@develop
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: "./startup.sh"
